/**
 * Markdown emission.
 *
 * The pages are plain Markdown rather than a component reading a data file
 * because this site exposes its content four ways that all read the Markdown
 * body — `nuxt-llms`, the MCP `get-page` tool, the `/raw/*.md` route, and the
 * built-in search. An objective that lives only in a JSON file would be
 * missing from all four, which is most of the point of indexing it.
 *
 * Objectives are listed one per line under an A–Z heading rather than each
 * getting a heading of its own: the largest region holds nearly 500 of them,
 * and a heading each would put 500 entries in the table of contents. Twenty-six
 * letters is a table of contents worth having.
 */
import type { Objective, RawReport } from './types.ts'
import type { Region } from './regions.ts'
import { UNSORTED } from './regions.ts'
import { SOURCES } from './sources/index.ts'

const LABELS = new Map(SOURCES.map(source => [source.id, source.label]))

const GENERATED_NOTE
  = '<!-- Generated by `mise run build-trip-index`. Do not edit by hand:\n'
    + '     changes are overwritten on the next run. Corrections go in\n'
    + '     scripts/trip-report-index/curation.ts. -->'

/** Markdown special characters that appear in real objective names. */
function escapeText(value: string): string {
  return value.replace(/([\\`*_[\]<>])/g, '\\$1')
}

function escapeTitle(value: string): string {
  return value.replace(/"/g, '”')
}

/**
 * One source link. The report's own title becomes the link's tooltip when it
 * differs from the objective, which is how a combined trip announces itself
 * without repeating "(+ Courcelette, Fording)" on every peak it covers.
 */
function renderLink(report: RawReport, objectiveName: string): string {
  const label = LABELS.get(report.sourceId) ?? report.sourceId
  const title = report.title.trim()
  const differs = title.toLowerCase() !== objectiveName.toLowerCase()
  const tooltip = differs ? ` "${escapeTitle(title)}"` : ''
  return `[${label}](${report.url}${tooltip})`
}

/**
 * The guidebooks an objective appears in, each linking to Adam Laycock's page
 * for it. The books are not online, so there is nothing else to point at; his
 * list is the closest published record of what each one contains, and a reader
 * who wants the route description goes to the book itself.
 */
function renderGuidebooks(objective: Objective): string {
  if (!objective.guidebooks?.length) return ''
  const marks = objective.guidebooks
    .map(entry => `[${escapeText(entry.book)} — ${escapeText(entry.grade)}](${entry.url})`)
    .join(', ')
  return ` · ${marks}`
}

function renderObjective(objective: Objective): string {
  const links = objective.reports.map(report => renderLink(report, objective.name)).join(', ')
  const range = objective.subRange ? ` *(${escapeText(objective.subRange)})*` : ''
  return `- **${escapeText(objective.name)}**${range} — ${links}${renderGuidebooks(objective)}`
}

/** A–Z buckets; anything not starting with a letter collects under "#". */
function bucketOf(objective: Objective): string {
  const first = objective.name.replace(/^[^\p{L}\p{N}]+/u, '').charAt(0).toUpperCase()
  return /\p{L}/u.test(first) ? first : '#'
}

function groupByLetter(objectives: readonly Objective[]): Map<string, Objective[]> {
  const buckets = new Map<string, Objective[]>()
  for (const objective of objectives) {
    const letter = bucketOf(objective)
    if (!buckets.has(letter)) buckets.set(letter, [])
    buckets.get(letter)!.push(objective)
  }
  return new Map([...buckets].sort((left, right) => left[0].localeCompare(right[0])))
}

/**
 * The two sibling pages for the same region, rendered as buttons in the page
 * header. This is the payoff of the shared taxonomy in ADR-006 — the three
 * sections differ only in the section part of the path, so the links are
 * derivable rather than curated, and `checkMirroredSections` in main.ts has
 * already failed the run if either target is missing.
 *
 * The catch-all page is the exception: it is not a region and has no sibling.
 */
function crossLinks(region: Region): string[] {
  if (region.id === UNSORTED.id) return []
  return [
    'links:',
    '  - label: Weather',
    '    icon: i-lucide-cloud-sun',
    `    to: /weather-trail-conditions/popular-locations/${region.id}`,
    '  - label: Accommodation',
    '    icon: i-lucide-tent-tree',
    `    to: /accommodation/${region.id}`
  ]
}

/**
 * Repeated in the body as well as the header, because the header buttons are a
 * Vue concern and the Markdown body is what `nuxt-llms`, the MCP `get-page`
 * tool, the `/raw/*.md` route and the built-in search actually read — the same
 * reason these pages are Markdown at all.
 */
function crossLinkLine(region: Region): string[] {
  if (region.id === UNSORTED.id) return []
  return [
    `Planning a trip here? Check the [forecast](/weather-trail-conditions/popular-locations/${region.id})`,
    `and find [somewhere to sleep](/accommodation/${region.id}) for the same area.`,
    ''
  ]
}

function frontmatter(region: Region): string {
  return ['---',
    `title: ${region.title}`,
    `description: ${region.description}`,
    'navigation:',
    `  icon: ${region.icon}`,
    ...crossLinks(region),
    '---'].join('\n')
}

function summary(objectives: readonly Objective[]): string {
  const total = objectives.length
  const corroborated = objectives.filter(objective => sourceCount(objective) > 1).length
  const sources = new Set(objectives.flatMap(o => o.reports.map(report => report.sourceId))).size
  return `${total} objective${total === 1 ? '' : 's'} indexed from ${sources} `
    + `blog${sources === 1 ? '' : 's'}, ${corroborated} of them with reports from more than one.`
}

function sourceCount(objective: Objective): number {
  return new Set(objective.reports.map(report => report.sourceId)).size
}

/**
 * Shown only on the catch-all page, to say why an objective is on it rather
 * than on a region page.
 */
const UNSORTED_NOTE = [
  'Four of the source blogs publish no region anywhere — not in a URL, a tag, a category, or a',
  'field on the page. Their reports do mention regions in passing, but a trip report names the',
  'valley you drove up, the range you were looking at, and the park you walked near, so the',
  'mention is right less than half the time when checked against objectives other blogs place.',
  '',
  'Rather than file these on a guess, they are listed together here. An objective leaves this',
  'page as soon as another blog covers it, or when its region is recorded by hand in the',
  'index\u2019s curation file.'
]

export function renderRegionPage(region: Region, objectives: readonly Objective[]): string {
  const sections = [...groupByLetter(objectives)].map(([letter, group]) =>
    [`## ${letter}`, '', ...group.map(renderObjective)].join('\n'))

  return [
    frontmatter(region),
    '',
    GENERATED_NOTE,
    '',
    summary(objectives),
    '',
    ...crossLinkLine(region),
    'Each entry links every trip report, video, or GPS trace the indexed blogs published',
    'for that objective. Hover a link to see the report’s own title, which is how',
    'combined trips and traverses show what else they cover.',
    '',
    'Where an objective appears in a guidebook, that is marked after the links with the',
    'book\u2019s own grade — Kane and Nugara for scrambles, *Don\u2019t Waste Your Time* for hikes.',
    'None of the three is published online, so the mark links to',
    '[Adam Laycock\u2019s page](https://adamlaycock.ca/Lists/) for that objective, which records',
    'the grade and little else. The route description is in the book.',
    '',
    ...(region.id === 'unsorted' ? [...UNSORTED_NOTE, ''] : []),
    ...sections.flatMap(section => [section, '']),
    'Reports are the authors’ own accounts of one day in particular conditions, not route',
    'descriptions that stay true. Check current [conditions](/weather-trail-conditions) and',
    'carry the judgement the terrain needs.',
    ''
  ].join('\n')
}
